In [2]:
from scipy.optimize import fsolve
from matplotlib import pyplot as plt
import numpy as np
from scipy.integrate import odeint
%matplotlib inline

In [3]:
"""5.2"""
ki = 0.0001
kinew = 0
pc = 1600
R = 1E-3
De = 5E-9

while abs(ki - kinew) > 1E-9:
    ki = kinew
    O = (ki*pc*(R**2)/De)**0.5

    if O > 20:
        n = 3/O
    elif 20 > O > 2:
        n = 3/(O**2)*(O/np.tanh(O) - 1)
    else:
        n = 1

    kinew = 4.363289E-5/n

def func(ki):
    O = (ki*pc*(R**2)/De)**0.5

    if O > 20:
        n = 3/O
    elif 20 > O > 2:
        n = 3/(O**2)*(O/np.tanh(O) - 1)
    else:
        n = 1

    kinew = 4.363289E-5/n

    return (kinew - ki)

Ki = fsolve(func,0.0001)
   
print (ki)
O = 18.3995018

n = 3/(O**2)*(O/np.tanh(O) - 1)
n


9.9899408225e-05


0.15418635449358759

In [4]:
"""5.2"""
ki = 0.0001
kinew = 0
pc = 1600
R = 1E-3
De = 5E-9

while abs(ki - kinew) > 1E-9:
    ki = kinew
    O = (ki*pc*(R**2)/De)**0.5

    if O > 20:
        n = 3/O
    elif 20 > O > 2:
        n = 3/(O**2)*(O/np.tanh(O) - 1)
    else:
        n = 1

    kinew = 4.363289E-5/n

def func(ki):
    O = (ki*pc*(R**2)/De)**0.5

    if O > 20:
        n = 3/O
    elif 20 > O > 2:
        n = 3/(O**2)*(O/np.tanh(O) - 1)
    else:
        n = 1

    kinew = 4.363289E-5/n

    return (kinew - ki)

Ki = fsolve(func,0.0001)
   
print (ki)
O = 18.3995018

n = 3/(O**2)*(O/np.tanh(O) - 1)
n


9.9899408225e-05


0.15418635449358759

In [5]:
pc = 2500
R = 0.5E-3
De = 7E-8

def func(ki):
    O = (ki*pc*(R**2)/De)**0.5

    if O > 20:
        n = 3/O
    elif 20 > O > 2:
        n = 3/(O**2)*(O/np.tanh(O) - 1)
    else:
        n = 1

    kinew = 4E-3/n
#     print (n)
    return (kinew - ki)

Ki = fsolve(func,0.1)
   
print (Ki)

O = (Ki*pc*(R**2)/De)**0.5
if O > 20:
    n = 3/O
elif 20 > O > 2:
    n = 3/(O**2)*(O/np.tanh(O) - 1)
else:
    n = 1

n


[ 0.01865168]


array([ 0.21445786])

In [13]:
"""5.7 a"""
def Ofunc(O):
    n = 3/(O**2)*(O/np.tanh(O) - 1)
    return n - 0.63734173

Oans = fsolve(Ofunc,5)
ki = 2.5252e-3
De = 7e-8
pc = 2500
def func(R):
    O = (ki*pc*(R**2)/De)**0.5
    return O - Oans

R = fsolve(func,0.0001)
R*2*1000

array([ 0.69267176])

In [24]:
"""5.7 b"""
pc = 2500
R = 1.5e-3
De = 7E-8
nki = 1.609437912e-3

def func(ki):
    O = (ki*pc*(R**2)/De)**0.5

    if O > 20:
        n = 3/O
    elif 20 > O > 2:
        n = 3/(O**2)*(O/np.tanh(O) - 1)
    else:
        n = 1

    kinew = nki/n
#     print (n)
    return (kinew - ki)

Ki = fsolve(func,1)
   
print (Ki)
Ko = 248.79
def rate(T):
    ki = Ko*np.exp(-50000/(8.134*T))
    return ki - Ki

Temp = fsolve(rate,300)
Temp -273.15

[ 0.02312759]


array([ 389.00806169])